version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:6.2-alpine3.14
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./data:/bitnami/redis/data
    restart: always
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: carlonicora
