name: Dev

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
      
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v2.2.1
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env file
        run: |
          cat > .env << EOF
          NEXT_PUBLIC_API_URL=http://localhost:3000
          NEXT_PUBLIC_ADDRESS=http://localhost:3001
          NEXT_PUBLIC_VAPID_PUBLIC_KEY=placeholder
          EOF

      - name: Build
        run: pnpm run build
      
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm dlx semantic-release